ENCHANTING_PRICE_MULT = 0.5


function getRecord(recordType, recordId)
	recordType = string.lower(recordType)
	recordId = string.lower(recordId)
	
	if not RecordStores[recordType].data.permanentRecords[recordId] then
		RecordStores[recordType].data.permanentRecords[recordId] = { baseId = recordId}
	end
	
	return RecordStores[recordType].data.permanentRecords[recordId]
end


local function OnServerPostInit(eventStatus)
getRecord("miscellaneous", "artifact_bittercup_01").value = 10000
getRecord("miscellaneous", "misc_vivec_ashmask_01").value = 5000
getRecord("weapon", "6th bell hammer").value = 1000
getRecord("weapon", "adamantium_axe").value = 2500
getRecord("weapon", "adamantium_claymore").value = 5000
getRecord("weapon", "adamantium_mace").value = 500
getRecord("weapon", "adamantium_shortsword").value = 500
getRecord("weapon", "adamantium_spear").value = 1000
getRecord("weapon", "axe_queen_of_bats_unique").value = 3300
getRecord("weapon", "bipolar blade").value = 5300
getRecord("weapon", "bipolar blade_x").value = 5300
getRecord("weapon", "bm ice dagger").value = 1500
getRecord("weapon", "bm ice longsword").value = 6500
getRecord("weapon", "bm ice longsword_fg_unique").value = 6500
getRecord("weapon", "bm ice mace").value = 4000
getRecord("weapon", "bm ice war axe").value = 5000
getRecord("weapon", "bm nordic pick").value = 3000
getRecord("weapon", "bm nordic silver axe").value = 500
getRecord("weapon", "bm nordic silver battleaxe").value = 500
getRecord("weapon", "bm nordic silver claymore").value = 500
getRecord("weapon", "bm nordic silver dagger").value = 500
getRecord("weapon", "bm nordic silver longsword").value = 500
getRecord("weapon", "bm nordic silver mace").value = 500
getRecord("weapon", "bm nordic silver shortsword").value = 500
getRecord("weapon", "bm_axe_heartfang_unique").value = 1200
getRecord("weapon", "bm_ebony_staff_necro").value = 2900
getRecord("weapon", "bm_ebonylongsword_s").value = 2600
getRecord("weapon", "bm_hunterspear_unique").value = 4400
getRecord("weapon", "bm_mace_aevar_uni").value = 5800
getRecord("weapon", "boethiah's walking stick").value = 4100
getRecord("weapon", "claymore_chrysamere_unique").value = 9500
getRecord("weapon", "claymore_chrysamere_unique_x").value = 9500
getRecord("weapon", "claymore_iceblade_unique").value = 9500
getRecord("weapon", "claymore_iceblade_unique_x").value = 9500
getRecord("weapon", "cleaverstfelms").value = 3300
getRecord("weapon", "clutterbane").value = 5800
getRecord("weapon", "conoon_chodala_axe_unique").value = 3300
getRecord("weapon", "crosierstllothis").value = 2600
getRecord("weapon", "daedric battle axe").value = 5000
getRecord("weapon", "daedric claymore").value = 8000
getRecord("weapon", "daedric club").value = 1000
getRecord("weapon", "daedric dagger").value = 1000
getRecord("weapon", "daedric dagger_bar").value = 3100
getRecord("weapon", "daedric dagger_mtas").value = 3600
getRecord("weapon", "daedric dagger_soultrap").value = 3200
getRecord("weapon", "daedric dai-katana").value = 12000
getRecord("weapon", "daedric dart").value = 400
getRecord("weapon", "daedric katana").value = 5000
getRecord("weapon", "daedric long bow").value = 5000
getRecord("weapon", "daedric longsword").value = 4000
getRecord("weapon", "daedric mace").value = 2400
getRecord("weapon", "daedric shortsword").value = 2000
getRecord("weapon", "daedric spear").value = 2000
getRecord("weapon", "daedric staff").value = 1400
getRecord("weapon", "daedric tanto").value = 1400
getRecord("weapon", "daedric wakizashi").value = 4800
getRecord("weapon", "daedric wakizashi_hhst").value = 4800
getRecord("weapon", "daedric war axe").value = 3000
getRecord("weapon", "daedric warhammer").value = 3000
getRecord("weapon", "daedric warhammer_ttgd").value = 4700
getRecord("weapon", "daedric warhammer_ttgd_x").value = 4700
getRecord("weapon", "daedric_club_tgdc").value = 1000
getRecord("weapon", "daedric_crescent_unique").value = 18000
getRecord("weapon", "daedric_scourge_unique").value = 8000
getRecord("weapon", "dagger_fang_unique").value = 4800
getRecord("weapon", "dagger_fang_unique_x").value = 4800
getRecord("weapon", "daunting mace").value = 3400
getRecord("weapon", "demon katana").value = 3100
getRecord("weapon", "demon longbow").value = 3200
getRecord("weapon", "demon mace").value = 3100
getRecord("weapon", "ebony broadsword").value = 1500
getRecord("weapon", "ebony broadsword_dae_cursed").value = 1500
getRecord("weapon", "ebony dart").value = 200
getRecord("weapon", "ebony dart_db_unique").value = 200
getRecord("weapon", "ebony longsword").value = 2000
getRecord("weapon", "ebony mace").value = 1200
getRecord("weapon", "ebony scimitar").value = 1500
getRecord("weapon", "ebony scimitar_her").value = 4400
getRecord("weapon", "ebony shortsword").value = 1000
getRecord("weapon", "ebony shortsword_soscean").value = 3200
getRecord("weapon", "ebony spear").value = 1000
getRecord("weapon", "ebony spear_blessed_unique").value = 3100
getRecord("weapon", "ebony spear_hrce_unique").value = 3100
getRecord("weapon", "ebony staff").value = 700
getRecord("weapon", "ebony staff caper").value = 2500
getRecord("weapon", "ebony throwing star").value = 200
getRecord("weapon", "ebony war axe").value = 1500
getRecord("weapon", "ebony war axe_elanande").value = 3600
getRecord("weapon", "ebony wizard's staff").value = 3100
getRecord("weapon", "ebony_bow_auriel").value = 4700
getRecord("weapon", "ebony_bow_auriel_x").value = 4700
getRecord("weapon", "ebony_dagger_mehrunes").value = 500
getRecord("weapon", "ebony_staff_tges").value = 2500
getRecord("weapon", "ebony_staff_trebonius").value = 3100
getRecord("weapon", "fiend battle axe").value = 3000
getRecord("weapon", "fiend katana").value = 3000
getRecord("weapon", "fiend longbow").value = 3000
getRecord("weapon", "fiend spear").value = 2300
getRecord("weapon", "fiend spear_dae_cursed").value = 2300
getRecord("weapon", "fiend tanto").value = 2300
getRecord("weapon", "fury").value = 2300
getRecord("weapon", "glass claymore").value = 3200
getRecord("weapon", "glass claymore_magebane").value = 4800
getRecord("weapon", "glass dagger").value = 400
getRecord("weapon", "glass dagger_dae_cursed").value = 400
getRecord("weapon", "glass dagger_symmachus_unique").value = 4000
getRecord("weapon", "glass dagger_symmachus_unique_x").value = 4000
getRecord("weapon", "glass firesword").value = 3800
getRecord("weapon", "glass frostsword").value = 3800
getRecord("weapon", "glass halberd").value = 1600
getRecord("weapon", "glass jinkblade").value = 2700
getRecord("weapon", "glass longsword").value = 1600
getRecord("weapon", "glass netch dagger").value = 2600
getRecord("weapon", "glass poisonsword").value = 3800
getRecord("weapon", "glass staff").value = 560
getRecord("weapon", "glass stormblade").value = 2700
getRecord("weapon", "glass stormsword").value = 3800
getRecord("weapon", "glass war axe").value = 1200
getRecord("weapon", "glass_dagger_enamor").value = 400
getRecord("weapon", "goblin_club").value = 300
getRecord("weapon", "gravedigger").value = 12000
getRecord("weapon", "hf_eco_iron arrow").value = 0
getRecord("weapon", "hf_eco_iron bolt").value = 0
getRecord("weapon", "katana_bluebrand_unique").value = 15000
getRecord("weapon", "katana_goldbrand_unique").value = 15000
getRecord("weapon", "katana_goldbrand_unique_x").value = 15000
getRecord("weapon", "keening").value = 40000
getRecord("weapon", "king's_oath").value = 8000
getRecord("weapon", "king's_oath_pc").value = 8000
getRecord("weapon", "lightofday_unique").value = 2200
getRecord("weapon", "longbow_shadows_unique").value = 5400
getRecord("weapon", "longbow_shadows_unique_x").value = 5400
getRecord("weapon", "longsword_umbra_unique").value = 11000
getRecord("weapon", "longsword_umbra_unique_x").value = 11000
getRecord("weapon", "mace of molag bal_unique").value = 4400
getRecord("weapon", "mace of molag bal_unique_x").value = 4400
getRecord("weapon", "mace of slurring").value = 4000
getRecord("weapon", "mace of slurring_x").value = 4000
getRecord("weapon", "mehrunes'_razor_unique").value = 2600
getRecord("weapon", "mephala's teacher").value = 3400
getRecord("weapon", "nerevarblade_01").value = 3600
getRecord("weapon", "nerevarblade_01_flame").value = 15000
getRecord("weapon", "nordic claymore_stormfang").value = 3100
getRecord("weapon", "orcish battle axe").value = 500
getRecord("weapon", "orcish warhammer").value = 400
getRecord("weapon", "saint's black sword").value = 3400
getRecord("weapon", "spear_mercy_unique").value = 13000
getRecord("weapon", "spear_mercy_unique_x").value = 13000
getRecord("weapon", "spirit-eater").value = 4400
getRecord("weapon", "staff of the forefathers").value = 3100
getRecord("weapon", "staff_hasedoki_unique").value = 7500
getRecord("weapon", "staff_hasedoki_unique_x").value = 7500
getRecord("weapon", "staff_magnus_unique").value = 21000
getRecord("weapon", "staff_magnus_unique_x").value = 21000
getRecord("weapon", "steel jinkblade of the aegis").value = 2800
getRecord("weapon", "steelstaffancestors_ttsa").value = 2900
getRecord("weapon", "stendar_hammer_unique").value = 13000
getRecord("weapon", "stendar_hammer_unique_x").value = 13000
getRecord("weapon", "sunder").value = 40000
getRecord("weapon", "sword of almalexia").value = 15000
getRecord("weapon", "sword of white woe").value = 3800
getRecord("weapon", "war_axe_airan_ammu").value = 3500
getRecord("weapon", "warhammer_crusher_unique").value = 5700
getRecord("weapon", "warhammer_crusher_unique_x").value = 5700
getRecord("weapon", "we_hellfirestaff").value = 3000
getRecord("weapon", "we_shimsil").value = 3100
getRecord("weapon", "we_temreki").value = 2500
getRecord("weapon", "widowmaker_unique").value = 2100
getRecord("weapon", "wild flameblade").value = 2400
getRecord("weapon", "wild shardblade").value = 2400
getRecord("weapon", "wild sparkblade").value = 2400
getRecord("weapon", "wild viperblade").value = 2400
getRecord("armor", "adamantium boots").value = 1400
getRecord("armor", "adamantium_bracer_left").value = 400
getRecord("armor", "adamantium_bracer_right").value = 400
getRecord("armor", "adamantium_cuirass").value = 2000
getRecord("armor", "adamantium_greaves").value = 2000
getRecord("armor", "adamantium_helm").value = 1000
getRecord("armor", "addamantium_helm").value = 1000
getRecord("armor", "azura's servant").value = 4700
getRecord("armor", "bloodworm_helm_unique").value = 4900
getRecord("armor", "bloodworm_helm_unique_x").value = 4900
getRecord("armor", "bm_bear_boots_snow").value = 1000
getRecord("armor", "bm_bear_cuirass_snow").value = 2000
getRecord("armor", "bm_bear_greaves_snow").value = 1700
getRecord("armor", "bm_bear_helmet_snow").value = 700
getRecord("armor", "bm_bear_left_gauntlet_snow").value = 400
getRecord("armor", "bm_bear_left_pauldron_snow").value = 400
getRecord("armor", "bm_bear_right_gauntlet_snow").value = 400
getRecord("armor", "bm_bear_right_pauldron_snow").value = 400
getRecord("armor", "bm_ice_boots").value = 2500
getRecord("armor", "bm_ice_cuirass").value = 2500
getRecord("armor", "bm_ice_gauntletl").value = 500
getRecord("armor", "bm_ice_gauntletr").value = 500
getRecord("armor", "bm_ice_helmet").value = 1000
getRecord("armor", "bm_ice_pauldronl").value = 600
getRecord("armor", "bm_ice_pauldronr").value = 600
getRecord("armor", "bm_nordicmail_boots").value = 2500
getRecord("armor", "bm_nordicmail_cuirass").value = 2500
getRecord("armor", "bm_nordicmail_gauntletl").value = 500
getRecord("armor", "bm_nordicmail_gauntletr").value = 500
getRecord("armor", "bm_nordicmail_greaves").value = 1000
getRecord("armor", "bm_nordicmail_helmet").value = 500
getRecord("armor", "bm_nordicmail_pauldronl").value = 500
getRecord("armor", "bm_nordicmail_pauldronr").value = 500
getRecord("armor", "bm_nordicmail_shield").value = 500
getRecord("armor", "bm_wolf_boots_snow").value = 1000
getRecord("armor", "bm_wolf_cuirass_snow").value = 2000
getRecord("armor", "bm_wolf_greaves_snow").value = 1700
getRecord("armor", "bm_wolf_helmet_snow").value = 700
getRecord("armor", "bm_wolf_left_gauntlet_snow").value = 400
getRecord("armor", "bm_wolf_left_pauldron_snow").value = 400
getRecord("armor", "bm_wolf_right_gauntlet_snow").value = 400
getRecord("armor", "bm_wolf_right_pauldron_snow").value = 400
getRecord("armor", "boots of blinding speed[unique]").value = 2500
getRecord("armor", "boots of blinding speed_x").value = 2500
getRecord("armor", "boots_apostle_unique").value = 6000
getRecord("armor", "boots_apostle_unique_x").value = 6000
getRecord("armor", "cuirass_savior_unique").value = 15000
getRecord("armor", "cuirass_savior_unique_x").value = 15000
getRecord("armor", "daedric_boots").value = 2000
getRecord("armor", "daedric_cuirass").value = 7000
getRecord("armor", "daedric_cuirass_htab").value = 8600
getRecord("armor", "daedric_fountain_helm").value = 1300
getRecord("armor", "daedric_gauntlet_left").value = 1400
getRecord("armor", "daedric_gauntlet_right").value = 1400
getRecord("armor", "daedric_god_helm").value = 1500
getRecord("armor", "daedric_greaves").value = 4400
getRecord("armor", "daedric_greaves_htab").value = 6000
getRecord("armor", "daedric_helm_clavicusvile").value = 3600
getRecord("armor", "daedric_pauldron_left").value = 2400
getRecord("armor", "daedric_pauldron_right").value = 2400
getRecord("armor", "daedric_shield").value = 3400
getRecord("armor", "daedric_terrifying_helm").value = 1400
getRecord("armor", "daedric_towershield").value = 5000
getRecord("armor", "darkbrotherhood boots").value = 100
getRecord("armor", "darkbrotherhood cuirass").value = 200
getRecord("armor", "darkbrotherhood gauntlet_l").value = 40
getRecord("armor", "darkbrotherhood gauntlet_r").value = 40
getRecord("armor", "darkbrotherhood helm").value = 40
getRecord("armor", "darkbrotherhood pauldron_l").value = 100
getRecord("armor", "darkbrotherhood pauldron_r").value = 100
getRecord("armor", "darksun_shield_unique").value = 3800
getRecord("armor", "dragonbone_cuirass_unique").value = 18000
getRecord("armor", "dragonbone_cuirass_unique_x").value = 18000
getRecord("armor", "dreugh_cuirass").value = 1050
getRecord("armor", "dreugh_cuirass_ttrm").value = 2550
getRecord("armor", "dreugh_helm").value = 450
getRecord("armor", "dreugh_shield").value = 510
getRecord("armor", "ebon_plate_cuirass_unique").value = 12000
getRecord("armor", "ebon_plate_cuirass_unique_x").value = 12000
getRecord("armor", "ebony_boots").value = 1000
getRecord("armor", "ebony_bracer_left").value = 500
getRecord("armor", "ebony_bracer_left_tgeb").value = 500
getRecord("armor", "ebony_bracer_right").value = 500
getRecord("armor", "ebony_bracer_right_tgeb").value = 500
getRecord("armor", "ebony_closed_helm").value = 1500
getRecord("armor", "ebony_closed_helm_fghl").value = 1500
getRecord("armor", "ebony_cuirass").value = 3500
getRecord("armor", "ebony_cuirass_soscean").value = 4800
getRecord("armor", "ebony_greaves").value = 2200
getRecord("armor", "ebony_pauldron_left").value = 1200
getRecord("armor", "ebony_pauldron_right").value = 1200
getRecord("armor", "ebony_shield").value = 1700
getRecord("armor", "ebony_shield_auriel").value = 3800
getRecord("armor", "ebony_shield_auriel_x").value = 3800
getRecord("armor", "ebony_towershield").value = 2500
getRecord("armor", "fiend helm").value = 2700
getRecord("armor", "gauntlet_fists_l_unique").value = 5000
getRecord("armor", "gauntlet_fists_r_unique").value = 5000
getRecord("armor", "glass_boots").value = 800
getRecord("armor", "glass_bracer_left").value = 400
getRecord("armor", "glass_bracer_right").value = 400
getRecord("armor", "glass_cuirass").value = 2800
getRecord("armor", "glass_greaves").value = 1760
getRecord("armor", "glass_helm").value = 1200
getRecord("armor", "glass_pauldron_left").value = 960
getRecord("armor", "glass_pauldron_right").value = 960
getRecord("armor", "glass_shield").value = 1360
getRecord("armor", "glass_towershield").value = 2000
getRecord("armor", "goblin_shield").value = 100
getRecord("armor", "helm of holy fire").value = 2900
getRecord("armor", "helm_bearclaw_unique").value = 13000
getRecord("armor", "helm_bearclaw_unique_x").value = 13000
getRecord("armor", "helsethguard_boots").value = 500
getRecord("armor", "helsethguard_cuirass").value = 1600
getRecord("armor", "helsethguard_gauntlet_left").value = 400
getRecord("armor", "helsethguard_gauntlet_right").value = 400
getRecord("armor", "helsethguard_greaves").value = 400
getRecord("armor", "helsethguard_pauldron_left").value = 600
getRecord("armor", "helsethguard_pauldron_right").value = 600
getRecord("armor", "hf_eco_fur_colovian_helm").value = 0
getRecord("armor", "holy_tower_shield").value = 2200
getRecord("armor", "indoril boots").value = 400
getRecord("armor", "indoril cuirass").value = 1400
getRecord("armor", "indoril helmet").value = 600
getRecord("armor", "indoril left gauntlet").value = 280
getRecord("armor", "indoril pauldron left").value = 480
getRecord("armor", "indoril pauldron right").value = 480
getRecord("armor", "indoril right gauntlet").value = 280
getRecord("armor", "indoril shield").value = 400
getRecord("armor", "indoril_almalexia_boots").value = 2000
getRecord("armor", "indoril_almalexia_cuirass").value = 5500
getRecord("armor", "indoril_almalexia_gauntlet_l").value = 1800
getRecord("armor", "indoril_almalexia_gauntlet_r").value = 1800
getRecord("armor", "indoril_almalexia_greaves").value = 3800
getRecord("armor", "indoril_almalexia_helmet").value = 1700
getRecord("armor", "indoril_almalexia_pauldron_l").value = 2500
getRecord("armor", "indoril_almalexia_pauldron_r").value = 2500
getRecord("armor", "indoril_almalexia_shield").value = 3000
getRecord("armor", "indoril_mh_guard_boots").value = 1500
getRecord("armor", "indoril_mh_guard_cuirass").value = 5000
getRecord("armor", "indoril_mh_guard_gauntlet_l").value = 1300
getRecord("armor", "indoril_mh_guard_gauntlet_r").value = 1300
getRecord("armor", "indoril_mh_guard_greaves").value = 3300
getRecord("armor", "indoril_mh_guard_helmet").value = 1200
getRecord("armor", "indoril_mh_guard_pauldron_l").value = 2000
getRecord("armor", "indoril_mh_guard_pauldron_r").value = 2000
getRecord("armor", "lords_cuirass_unique").value = 19000
getRecord("armor", "lords_cuirass_unique_x").value = 19000
getRecord("armor", "mountain spirit").value = 2300
getRecord("armor", "orcish_boots").value = 200
getRecord("armor", "orcish_bracer_left").value = 100
getRecord("armor", "orcish_bracer_right").value = 100
getRecord("armor", "orcish_cuirass").value = 700
getRecord("armor", "orcish_greaves").value = 440
getRecord("armor", "orcish_helm").value = 300
getRecord("armor", "orcish_pauldron_left").value = 240
getRecord("armor", "orcish_pauldron_right").value = 240
getRecord("armor", "orcish_towershield").value = 500
getRecord("armor", "redoran_master_helm").value = 600
getRecord("armor", "saint's shield").value = 3600
getRecord("armor", "shadow_shield").value = 2100
getRecord("armor", "spell_breaker_unique").value = 11000
getRecord("armor", "spell_breaker_unique_x").value = 11000
getRecord("armor", "spirit of indoril").value = 2600
getRecord("armor", "succour of indoril").value = 2400
getRecord("armor", "tenpaceboots").value = 14000
getRecord("armor", "tenpaceboots_x").value = 14000
getRecord("armor", "towershield_eleidon_unique").value = 20000
getRecord("armor", "towershield_eleidon_unique_x").value = 20000
getRecord("armor", "wraithguard").value = 50000
getRecord("armor", "wraithguard_jury_rig").value = 3100
getRecord("clothing", "akatosh ring").value = 52429
getRecord("clothing", "akatosh's ring").value = 52429
getRecord("clothing", "amulet of 6th house").value = 0
getRecord("clothing", "artifact_amulet of heartfire").value = 0
getRecord("clothing", "artifact_amulet of heartheal").value = 0
getRecord("clothing", "artifact_amulet of heartrime").value = 0
getRecord("clothing", "artifact_amulet of heartthrum").value = 0
getRecord("clothing", "artifact_belt_of_heartfire").value = 0
getRecord("clothing", "artifact_blood_ring").value = 52429
getRecord("clothing", "artifact_heart_ring").value = 52429
getRecord("clothing", "artifact_soul_ring").value = 52429
getRecord("clothing", "belt of heartfire").value = 0
getRecord("clothing", "blood ring").value = 52429
getRecord("clothing", "bm_amulspd1").value = 0
getRecord("clothing", "bm_amulstr1").value = 0
getRecord("clothing", "bm_ring_aesliip").value = 52429
getRecord("clothing", "bm_ring_hircine").value = 52429
getRecord("clothing", "bm_ring_marksman").value = 52429
getRecord("clothing", "cl_ringofregeneration").value = 52429
getRecord("clothing", "daedric_special").value = 0
getRecord("clothing", "daedric_special01").value = 0
getRecord("clothing", "extravagant_belt_hf").value = 0
getRecord("clothing", "extravagant_rt_art_wild").value = 0
getRecord("clothing", "flamemirror robe").value = 0
getRecord("clothing", "heart ring").value = 52429
getRecord("clothing", "mantle of woe").value = 0
getRecord("clothing", "necromancers_amulet_uniq").value = 0
getRecord("clothing", "ring of azura").value = 52429
getRecord("clothing", "ring_denstagmer_unique").value = 39322
getRecord("clothing", "ring_equity_uniq").value = 52429
getRecord("clothing", "ring_fathasa_unique").value = 0
getRecord("clothing", "ring_khajiit_unique").value = 52429
getRecord("clothing", "ring_marara_unique").value = 52429
getRecord("clothing", "ring_mentor_unique").value = 52429
getRecord("clothing", "ring_phynaster_unique").value = 52429
getRecord("clothing", "ring_phynaster_unique_x").value = 52429
getRecord("clothing", "ring_shashev_unique").value = 52429
getRecord("clothing", "ring_surrounding_unique").value = 52429
getRecord("clothing", "ring_vampiric_unique").value = 52429
getRecord("clothing", "ring_vampiric_unique_x").value = 52429
getRecord("clothing", "ring_warlock_unique").value = 52429
getRecord("clothing", "ring_warlock_unique_x").value = 52429
getRecord("clothing", "ring_wind_unique").value = 52429
getRecord("clothing", "robe_lich_unique").value = 0
getRecord("clothing", "robe_lich_unique_x").value = 0
getRecord("clothing", "septim ring").value = 52429
getRecord("clothing", "sheogorath's signet ring").value = 52429
getRecord("clothing", "soul ring").value = 52429
getRecord("clothing", "teeth").value = 0
getRecord("clothing", "thong").value = 0
getRecord("clothing", "zenithar_whispers").value = 0
getRecord("repair", "hf_eco_repair_journeyman_01").value = 0
getRecord("apparatus", "apparatus_g_alembic_01").value = 2000
getRecord("apparatus", "apparatus_g_calcinator_01").value = 2000
getRecord("apparatus", "apparatus_g_mortar_01").value = 2000
getRecord("apparatus", "apparatus_g_retort_01").value = 800
getRecord("apparatus", "apparatus_m_alembic_01").value = 600
getRecord("apparatus", "apparatus_m_calcinator_01").value = 120
getRecord("apparatus", "apparatus_m_mortar_01").value = 1200
getRecord("apparatus", "apparatus_m_retort_01").value = 240
getRecord("apparatus", "apparatus_sm_alembic_01").value = 800
getRecord("apparatus", "apparatus_sm_calcinator_01").value = 1600
getRecord("apparatus", "apparatus_sm_mortar_01").value = 3000
getRecord("apparatus", "apparatus_sm_retort_01").value = 500
getRecord("ingredient", "ingred_alit_hide_01").value = 10
getRecord("ingredient", "ingred_ash_salts_01").value = 20
getRecord("ingredient", "ingred_bear_pelt").value = 30
getRecord("ingredient", "ingred_boar_leather").value = 20
getRecord("ingredient", "ingred_corprus_weepings_01").value = 30
getRecord("ingredient", "ingred_crab_meat_01").value = 5
getRecord("ingredient", "ingred_cursed_daedras_heart_01").value = 100
getRecord("ingredient", "ingred_daedra_skin_01").value = 75
getRecord("ingredient", "ingred_daedras_heart_01").value = 100
getRecord("ingredient", "ingred_dreugh_wax_01").value = 30
getRecord("ingredient", "ingred_durzog_meat_01").value = 20
getRecord("ingredient", "ingred_eyeball").value = 80
getRecord("ingredient", "ingred_eyeball_unique").value = 80
getRecord("ingredient", "ingred_fire_salts_01").value = 30
getRecord("ingredient", "ingred_frost_salts_01").value = 40
getRecord("ingredient", "ingred_ghoul_heart_01").value = 50
getRecord("ingredient", "ingred_guar_hide_01").value = 10
getRecord("ingredient", "ingred_guar_hide_girith").value = 10
getRecord("ingredient", "ingred_guar_hide_marsus").value = 10
getRecord("ingredient", "ingred_horker_tusk_01").value = 10
getRecord("ingredient", "ingred_hound_meat_01").value = 5
getRecord("ingredient", "ingred_kagouti_hide_01").value = 15
getRecord("ingredient", "ingred_netch_leather_01").value = 20
getRecord("ingredient", "ingred_racer_plumes_01").value = 15
getRecord("ingredient", "ingred_rat_meat_01").value = 3
getRecord("ingredient", "ingred_scales_01").value = 5
getRecord("ingredient", "ingred_scamp_skin_01").value = 25
getRecord("ingredient", "ingred_scrib_jelly_01").value = 5
getRecord("ingredient", "ingred_scrib_jelly_02").value = 5
getRecord("ingredient", "ingred_shalk_resin_01").value = 15
getRecord("ingredient", "ingred_snowbear_pelt_unique").value = 60
getRecord("ingredient", "ingred_snowwolf_pelt_unique").value = 40
getRecord("ingredient", "ingred_vampire_dust_01").value = 300
getRecord("ingredient", "ingred_void_salts_01").value = 50
getRecord("ingredient", "ingred_wolf_pelt").value = 10
getRecord("book", "bk_alchemistsformulary").value = 170
getRecord("book", "bk_bluebookofriddles").value = 150
getRecord("book", "bk_brothersofdarkness").value = 90
getRecord("book", "bk_chroniclesnchuleft").value = 150
getRecord("book", "bk_honorthieves").value = 90
getRecord("book", "bk_legendaryscourge").value = 120
getRecord("book", "bk_ngastakvatakvakis_c").value = 120
getRecord("book", "bk_ngastakvatakvakis_o").value = 120
getRecord("book", "bk_pigchildren").value = 90
getRecord("book", "bk_postingofthehunt").value = 120
getRecord("book", "bk_progressoftruth").value = 100
getRecord("book", "bk_saryonisermonsmanuscript").value = 5000
getRecord("book", "bk_spiritofthedaedra").value = 90
getRecord("book", "bk_vagariesofmagica").value = 120
getRecord("book", "bk_vampiresofvvardenfell2").value = 200
getRecord("book", "bk_watersofoblivion").value = 150
getRecord("book", "bookskill_acrobatics1").value = 120
getRecord("book", "bookskill_acrobatics2").value = 100
getRecord("book", "bookskill_acrobatics3").value = 100
getRecord("book", "bookskill_acrobatics4").value = 200
getRecord("book", "bookskill_acrobatics5").value = 150
getRecord("book", "bookskill_alchemy1").value = 120
getRecord("book", "bookskill_alchemy2").value = 120
getRecord("book", "bookskill_alchemy3").value = 120
getRecord("book", "bookskill_alchemy4").value = 120
getRecord("book", "bookskill_alchemy5").value = 120
getRecord("book", "bookskill_alteration1").value = 200
getRecord("book", "bookskill_alteration2").value = 150
getRecord("book", "bookskill_alteration3").value = 160
getRecord("book", "bookskill_alteration4").value = 120
getRecord("book", "bookskill_alteration5").value = 190
getRecord("book", "bookskill_armorer1").value = 180
getRecord("book", "bookskill_armorer2").value = 150
getRecord("book", "bookskill_armorer3").value = 120
getRecord("book", "bookskill_armorer4").value = 120
getRecord("book", "bookskill_armorer5").value = 120
getRecord("book", "bookskill_athletics1").value = 120
getRecord("book", "bookskill_athletics2").value = 100
getRecord("book", "bookskill_athletics3").value = 120
getRecord("book", "bookskill_athletics4").value = 120
getRecord("book", "bookskill_athletics5").value = 120
getRecord("book", "bookskill_axe1").value = 150
getRecord("book", "bookskill_axe2").value = 130
getRecord("book", "bookskill_axe3").value = 120
getRecord("book", "bookskill_axe4").value = 120
getRecord("book", "bookskill_axe5").value = 120
getRecord("book", "bookskill_axe5_open").value = 120
getRecord("book", "bookskill_block1").value = 170
getRecord("book", "bookskill_block2").value = 130
getRecord("book", "bookskill_block3").value = 100
getRecord("book", "bookskill_block4").value = 120
getRecord("book", "bookskill_block5").value = 120
getRecord("book", "bookskill_blunt weapon1").value = 150
getRecord("book", "bookskill_blunt weapon2").value = 120
getRecord("book", "bookskill_blunt weapon3").value = 160
getRecord("book", "bookskill_blunt weapon4").value = 120
getRecord("book", "bookskill_blunt weapon5").value = 120
getRecord("book", "bookskill_conjuration1").value = 170
getRecord("book", "bookskill_conjuration2").value = 170
getRecord("book", "bookskill_conjuration3").value = 160
getRecord("book", "bookskill_conjuration4").value = 160
getRecord("book", "bookskill_conjuration5").value = 180
getRecord("book", "bookskill_destruction1").value = 150
getRecord("book", "bookskill_destruction2").value = 120
getRecord("book", "bookskill_destruction3").value = 110
getRecord("book", "bookskill_destruction4").value = 130
getRecord("book", "bookskill_destruction5").value = 150
getRecord("book", "bookskill_destruction5_open").value = 150
getRecord("book", "bookskill_enchant1").value = 170
getRecord("book", "bookskill_enchant2").value = 150
getRecord("book", "bookskill_enchant3").value = 200
getRecord("book", "bookskill_enchant4").value = 120
getRecord("book", "bookskill_enchant5").value = 190
getRecord("book", "bookskill_hand to hand1").value = 150
getRecord("book", "bookskill_hand to hand2").value = 150
getRecord("book", "bookskill_hand to hand3").value = 170
getRecord("book", "bookskill_hand to hand4").value = 170
getRecord("book", "bookskill_hand to hand5").value = 170
getRecord("book", "bookskill_heavy armor1").value = 180
getRecord("book", "bookskill_heavy armor2").value = 160
getRecord("book", "bookskill_heavy armor3").value = 130
getRecord("book", "bookskill_heavy armor4").value = 120
getRecord("book", "bookskill_heavy armor5").value = 120
getRecord("book", "bookskill_illusion1").value = 150
getRecord("book", "bookskill_illusion2").value = 140
getRecord("book", "bookskill_illusion3").value = 130
getRecord("book", "bookskill_illusion4").value = 200
getRecord("book", "bookskill_illusion5").value = 150
getRecord("book", "bookskill_light armor1").value = 120
getRecord("book", "bookskill_light armor2").value = 180
getRecord("book", "bookskill_light armor3").value = 170
getRecord("book", "bookskill_light armor4").value = 120
getRecord("book", "bookskill_light armor5").value = 120
getRecord("book", "bookskill_long blade1").value = 130
getRecord("book", "bookskill_long blade2").value = 160
getRecord("book", "bookskill_long blade3").value = 120
getRecord("book", "bookskill_long blade4").value = 120
getRecord("book", "bookskill_long blade5").value = 120
getRecord("book", "bookskill_marksman1").value = 150
getRecord("book", "bookskill_marksman2").value = 100
getRecord("book", "bookskill_marksman3").value = 150
getRecord("book", "bookskill_marksman4").value = 150
getRecord("book", "bookskill_marksman5").value = 200
getRecord("book", "bookskill_medium armor1").value = 130
getRecord("book", "bookskill_medium armor2").value = 170
getRecord("book", "bookskill_medium armor3").value = 170
getRecord("book", "bookskill_medium armor4").value = 120
getRecord("book", "bookskill_medium armor5").value = 120
getRecord("book", "bookskill_mercantile1").value = 120
getRecord("book", "bookskill_mercantile2").value = 150
getRecord("book", "bookskill_mercantile3").value = 160
getRecord("book", "bookskill_mercantile4").value = 100
getRecord("book", "bookskill_mercantile5").value = 100
getRecord("book", "bookskill_mystery5").value = 150
getRecord("book", "bookskill_mysticism1").value = 120
getRecord("book", "bookskill_mysticism2").value = 160
getRecord("book", "bookskill_mysticism3").value = 120
getRecord("book", "bookskill_mysticism4").value = 120
getRecord("book", "bookskill_mysticism5").value = 170
getRecord("book", "bookskill_restoration1").value = 150
getRecord("book", "bookskill_restoration2").value = 160
getRecord("book", "bookskill_restoration3").value = 170
getRecord("book", "bookskill_restoration4").value = 160
getRecord("book", "bookskill_restoration5").value = 150
getRecord("book", "bookskill_security1").value = 120
getRecord("book", "bookskill_security2").value = 150
getRecord("book", "bookskill_security3").value = 170
getRecord("book", "bookskill_security4").value = 150
getRecord("book", "bookskill_security5").value = 190
getRecord("book", "bookskill_short blade1").value = 130
getRecord("book", "bookskill_short blade2").value = 160
getRecord("book", "bookskill_short blade3").value = 160
getRecord("book", "bookskill_short blade4").value = 120
getRecord("book", "bookskill_short blade5").value = 120
getRecord("book", "bookskill_sneak1").value = 150
getRecord("book", "bookskill_sneak2").value = 160
getRecord("book", "bookskill_sneak3").value = 120
getRecord("book", "bookskill_sneak4").value = 150
getRecord("book", "bookskill_sneak5").value = 120
getRecord("book", "bookskill_spear1").value = 150
getRecord("book", "bookskill_spear2").value = 160
getRecord("book", "bookskill_spear3").value = 120
getRecord("book", "bookskill_spear4").value = 120
getRecord("book", "bookskill_spear5").value = 120
getRecord("book", "bookskill_speechcraft1").value = 150
getRecord("book", "bookskill_speechcraft2").value = 150
getRecord("book", "bookskill_speechcraft3").value = 160
getRecord("book", "bookskill_speechcraft4").value = 150
getRecord("book", "bookskill_speechcraft5").value = 120
getRecord("book", "bookskill_unarmored1").value = 170
getRecord("book", "bookskill_unarmored2").value = 170
getRecord("book", "bookskill_unarmored3").value = 120
getRecord("book", "bookskill_unarmored4").value = 120
getRecord("book", "bookskill_unarmored5").value = 120
--getRecord("book", "hf_eco_bk_bookofdaedra").value = 0
--getRecord("book", "hf_eco_bk_invocationofazura").value = 0
--getRecord("book", "hf_eco_bk_originofthemagesguild").value = 0
--getRecord("book", "hf_eco_bk_specialfloraoftamriel").value = 0
--getRecord("book", "hf_eco_bk_spiritofthedaedra").value = 0
--getRecord("book", "hf_eco_bk_vagariesofmagica").value = 0
--getRecord("book", "hf_eco_sc_almsiviintervention").value = 0
--getRecord("book", "hf_eco_sc_daydenespanacea").value = 0
--getRecord("book", "hf_eco_sc_divineintervention").value = 0
--getRecord("potion", "hf_eco_p_fortify_willpower_s").value = 0
--getRecord("potion", "hf_eco_p_restore_fatigue_s").value = 0
--getRecord("potion", "hf_eco_p_restore_health_s").value = 0
--getRecord("potion", "hf_eco_p_restore_magicka_s").value = 0
--getRecord("potion", "hf_ecop_restore_health_c").value = 0
getRecord("potion", "p_quarrablood_unique").value = 3000
getRecord("potion", "potion_ancient_brandy").value = 1000
getRecord("potion", "potion_skooma_01").value = 300



RecordStores["gamesetting"].data.permanentRecords["iAlchemyMod"] = {floatVar = 0.5} -- from 2
RecordStores["gamesetting"].data.permanentRecords["fMagesGuildTravel"] = {floatVar = 40} -- from 10
RecordStores["gamesetting"].data.permanentRecords["fTravelMult"] = {floatVar = 1000} -- from 4000 (divisor)
RecordStores["gamesetting"].data.permanentRecords["iCrimeAttack"] = {intVar = 200} -- from 40
RecordStores["gamesetting"].data.permanentRecords["iCrimePickPocket"] = {intVar = 125} -- from 25
RecordStores["gamesetting"].data.permanentRecords["iCrimeTresspass"] = {intVar = 25} -- from 5
RecordStores["gamesetting"].data.permanentRecords["fEnchantmentValueMult"] = {floatVar = ENCHANTING_PRICE_MULT * 1000} -- from 1000

RecordStores["container"]:Save()
RecordStores["npc"]:Save()
RecordStores["creature"]:Save()
RecordStores["miscellaneous"]:Save()
RecordStores["weapon"]:Save()
RecordStores["armor"]:Save()
RecordStores["clothing"]:Save()
RecordStores["repair"]:Save()
RecordStores["apparatus"]:Save()
RecordStores["ingredient"]:Save()
RecordStores["book"]:Save()
RecordStores["potion"]:Save()
RecordStores["gamesetting"]:Save()
end

customEventHooks.registerHandler("OnServerPostInit", OnServerPostInit)

customEventHooks.registerValidator("OnObjectActivate",
function (eventStatus, pid, cellDescription, objects, players)
	local uniqueIndex = next(objects)
	local refId = objects[uniqueIndex].refId
	local cell = LoadedCells[cellDescription]
	local gold = nil
	if cell.data.objectData[uniqueIndex] ~= nil then
		gold = cell.data.objectData[uniqueIndex].goldPool
		lastRestockDay = cell.data.objectData[uniqueIndex].lastGoldRestockDay
		lastRestockHour = cell.data.objectData[uniqueIndex].lastGoldRestockHour
		setgold = nil
		
		if refId == "scamp_creeper" and (not gold or gold == 5000 or lastRestockDay and lastRestockDay < WorldInstance.data.time.daysPassed) then
			setgold = 500
		end
		if refId == "mudcrab_unique" and (not gold or gold == 10000 or lastRestockDay and lastRestockDay < WorldInstance.data.time.daysPassed) then
			setgold = 800
		end
		
		if setgold then
			print("[PriceBalance] Setting gold of "..refId)
			cell.data.objectData[uniqueIndex].goldPool = setgold
			cell.data.objectData[uniqueIndex].lastGoldRestockHour = WorldInstance.data.time.hour
			cell.data.objectData[uniqueIndex].lastGoldRestockDay = WorldInstance.data.time.daysPassed
			tes3mp.ClearObjectList()
			tes3mp.SetObjectListPid(pid)
			tes3mp.SetObjectListCell(cellDescription)
			packetBuilder.AddObjectMiscellaneous(uniqueIndex,{goldPool = setgold, lastGoldRestockHour = WorldInstance.data.time.hour,lastGoldRestockDay = WorldInstance.data.time.daysPassed})
			tes3mp.SendObjectMiscellaneous(true)
		elseif refId == "scamp_creeper" or refId == "mudcrab_unique" then
			print("[PriceBalance] Not changing gold of "..refId.." "..WorldInstance.data.time.daysPassed.." == "..lastRestockDay.." & gold = "..gold)
		end
		
		--for a,b in pairs(cell.data.objectData[uniqueIndex]) do
		--	print(a)
		--	print(b)
		--	print("------------")
		--end
		-- note: the server runs it's restock checks after this script
	end
end
)